//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMCFormTest.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANSWER_MULTICHOICE
    {
        public int ID { get; set; }
        public int ID_QUESTION { get; set; }
        public int NO { get; set; }
        public string ANSWER { get; set; }
        public bool CORRECT_ANSWER { get; set; }
    }
}
